name: Release - Conda

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

env:
  ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}

jobs:
  build_and_package:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: "build-datasets"
          python-version: 3.8
          channels: huggingface,conda-forge

      - name: Setup conda env
        run: |
          conda install -c defaults anaconda-client conda-build

      - name: Extract version
        run: echo "DATASETS_VERSION=`python setup.py --version`" >> $GITHUB_ENV

      - name: Build conda packages
        run: |
          conda info
          conda build .github/conda

      - name: Upload to Anaconda
        run: |
          anaconda upload `conda build .github/conda --output -c conda-forge` --force
