name: Update Hub repositories

on: push

jobs:
  update-hub-repositories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: Setup git config
        run: |
          git config --global user.name system
          git config --global user.email system@huggingface.co
      - name: Install dependencies
        working-directory: ./.github/hub
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update Hub repositories
        working-directory: ./.github/hub
        run: |
          export HF_TOKEN=${{ secrets.HUB_TRUSTED_COMMITER_TOKEN }}
          export DATASETS_LIB_PATH=$GITHUB_WORKSPACE
          python update_hub_repositories.py --auto
